MLE-12323/Dedicated-Known-Issues-CentOS-UBI
marklogic/marklogic-docker pull request #263
Opened 2024-02-28 16:54 UTC by rwinieski

### Description

#### Checklist: 

-  ##### Owner:

- [X] JIRA_ID as part of branch/PR name
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [ ] Added Tests
  
- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki/Jira

2024-02-28 19:33 UTC, vitalykorolev approved these changes

2024-03-21 00:48 UTC, jkerr5 requested changes
Let's rethink this as we discussed.

2024-04-23 08:40 UTC, jkerr5 requested changes

2024-04-23 08:40 UTC, jkerr5 commented on README.md
> +1. The image must be run in privileged mode. If the image isn't run as privileged many calls that use `sudo` during the supporting script will fail due to lack of required permissions as the image wi
The image must be run in privileged mode. If the image isn't run as privileged, the calls that use `sudo` in the startup script will fail due to lack of required permissions as the image will not be able to create a user with the required permissions. To run in non-privileged mode, use one of the “rootless” image options.

2024-04-23 08:53 UTC, jkerr5 approved these changes

2024-04-23 09:13 UTC, merged