MLE-13695 : Add Container Runtime Detection
marklogic/marklogic-docker pull request #273
Opened 2024-04-18 18:03 UTC by rwinieski

### Description

#### Checklist: 

-  ##### Owner:

- [X] JIRA_ID as part of branch/PR name
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  
- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki/Jira

2024-04-18 19:37 UTC, vitalykorolev requested changes
This PR contains some of the UBI/rootless changes

2024-04-19 16:26 UTC, vitalykorolev requested changes

2024-04-19 16:26 UTC, vitalykorolev commented on README.md
>  $ docker run -d -it -p 8000:8000 -p 8001:8001 -p 8002:8002 \
Are we removing all $ ?

2024-04-19 16:26 UTC, vitalykorolev commented on README.md
> +Create these files on your host machine: `marklogic-single-node.yaml`, `mldb_admin_username.txt`, `mldb_admin_password.txt`, and `mldb_wallet_password.txt`. Run the example Docker commands from the s
This is UBI/rootless related change

2024-04-19 16:26 UTC, vitalykorolev commented on README.md
> +Create these files on your host machine: `marklogic-single-node.yaml`, `mldb_admin_username.txt`, `mldb_admin_password.txt`, and `mldb_wallet_password.txt`. Run the example Docker commands from the s
And I see more of these below..

2024-04-19 16:26 UTC, vitalykorolev commented on README.md
> +`2024-03-15 08:27:36.136 Info: MarkLogic Server is running in a container using Docker runtime.A maximum of 1152 huge pages will be used if available`
Is that an actual log message? It's missing a space after the first sentence.

2024-04-23 08:37 UTC, jkerr5 requested changes

2024-04-23 08:37 UTC, jkerr5 commented on README.md
> +`2024-03-15 08:27:36.136 Info: MarkLogic Server is running in a container using Docker runtime. A maximum of 1152 huge pages will be used if available`
Change the log message examples to 
`Info: MarkLogic Server is running in a container using Docker runtime. A maximum of <x> huge pages will be used if available`

2024-04-23 08:37 UTC, jkerr5 commented on README.md
> +Since MarkLogic 11.2, MarkLogic is able to detect on which container runtime it is running on.
Starting with version 11.2, MarkLogic is able to detect which container runtime the container is running in.

2024-04-23 08:37 UTC, jkerr5 commented on README.md
> +`2024-03-15 08:27:36.136 Info: MarkLogic Server is running in a container using Docker runtime. A maximum of 1152 huge pages will be used if available`
Add

"Where <x> is calculated as described in the [Configuring HugePages](configuring-hugepages) section."

2024-04-23 08:37 UTC, jkerr5 commented on README.md
> +`2024-03-15 08:27:36.136 Info: MarkLogic Server is running in a container using Docker runtime. A maximum of 1152 huge pages will be used if available`
Do this for each of the container type sections.

2024-04-23 09:24 UTC, jkerr5 approved these changes

2024-04-23 17:29 UTC, vitalykorolev approved these changes

2024-04-24 07:41 UTC, merged